# Generated by Django 4.2.2 on 2023-07-07 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operateur',
            name='InSwitch',
        ),
        migrations.RemoveField(
            model_name='telecom',
            name='InSwitch',
        ),
    ]
